<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);vendor/**</DefaultItemExcludes>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>DH360D</AssemblyName>
    <RootNamespace>Dh360dFeed</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>assets\app.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <InvariantGlobalization>true</InvariantGlobalization>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <SupportedOSPlatformVersion>10.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="vendor\LibreHardwareMonitor\LibreHardwareMonitorLib\LibreHardwareMonitorLib.csproj" SetTargetFramework="TargetFramework=net8.0" />
  </ItemGroup>

  <ItemGroup Condition="Exists('driver\PawnIO_setup.exe')">
    <EmbeddedResource Include="driver\PawnIO_setup.exe" LogicalName="PawnIO_setup.exe" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\app.ico" LogicalName="app.ico" />
  </ItemGroup>

</Project>